name: Deploy Elysia + LibSQL

on:
  push:
    branches: ["main"]
    paths:
      - 'packages/backend/**'
      - 'docker-compose.yml'
      - '.gitea/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- NEW STEP: Create .env from GitHub Secrets ---
      - name: Create .env file
        run: |
          echo "ðŸ” Injecting Secrets..."
          
          # Option A: If you saved individual secrets
          # echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          # echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          
          # Option B: If you saved the WHOLE file as one secret (Recommended)
          echo "${{ secrets.PRODUCTION_ENV }}" > .env
          
          echo "âœ… .env file created!"

      - name: Deploy with Docker
        run: |
          echo "ðŸš€ Deploying Elysia..."
          
          # Pull latest images
          docker compose pull
          
          # Start Backend + LibSQL
          # We point to the .env file we just created
          docker compose --env-file .env up -d --build --remove-orphans
          
          
          # Cleanup
          docker image prune -f

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 1. Install the LATEST Vercel CLI (Fixes the version issue)
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # 2. Run Deploy manually
      # We inject the IDs as Environment Variables so Vercel knows who we are.
      # We use '--yes' to skip confirmation prompts.
      - name: Deploy to Vercel
        env:
          # If secrets work now, use ${{ secrets... }}
          # If secrets are still broken, PASTE YOUR HARDCODED IDs HERE for now
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel deploy --prod --token=$VERCEL_TOKEN --yes